### ISSUE TITLE
Could not resolve host: 'username'

### ISSUE THREAD

**Issue by moskalyk** [swisscom/gitlab-merge-request-resource#2]
For some reason, when performing the 'check' step, it does not resolve the host properly with the following error:

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/repo'...
fatal: unable to access 'https://username:password@gitlab.com/repo/project.git/': Couldn't resolve host 'username'
```

However, when I perform a git clone in my terminal, it clones the repo. Alternatively, when I clone it from an EC2 server, I get the same error as above.

**Comment by mastertinner** [comment]
When trying to clone in your local terminal, are you also using basic auth? You can also try to use the `debug` tag of the docker image which will give you a lot more information.

```yaml
resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: mastertinner/gitlab-merge-request-resource
    tag: debug
```
