### ISSUE TITLE
/opt/resource/out: line 61: ATC_EXTERNAL_URL: unbound variable

### ISSUE THREAD

**Issue by wuhuizuo** [swisscom/gitlab-merge-request-resource#22]
```yml
resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: mastertinner/gitlab-merge-request-resource
```
/opt/resource/out: line 61: ATC_EXTERNAL_URL: unbound variable
need this ENV var?
error when put to merge-request with updating merge status

**Comment by wuhuizuo** [comment]
hijack the container, and exec `env` cmd, output:
```text
LANG=C
BUILD_ID=62
USER=root
PWD=/tmp/build/put
HOME=/root
BUILD_PIPELINE_NAME=hci-testing
BUILD_TEAM_NAME=main
TERM=xterm-256color
BUILD_JOB_NAME=StaticQA-lib[Merge]
BUILD_NAME=1
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```

**Comment by mastertinner** [comment]
which version of Concourse are you using?

**Comment by wuhuizuo** [comment]
@mastertinner 

concourse `v3.9.1`

here is my docker-compose.yml(wirtten according to concourse [doc](https://concourse-ci.org/docker-repository.html) :
```yaml
version: '3'

volumes:
  concourse_db_data:

services:
  concourse-db:
    image: postgres:9.6
    volumes: ["concourse_db_data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: "${CONCOURSE_DB_USER:-concourse}"
      POSTGRES_PASSWORD: "${CONCOURSE_DB_PASSWORD:-changeme}"
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links:
      - concourse-db
    command: web
    depends_on:
      - concourse-db
    ports: ["80:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: "${CONCOURSE_USER:-concourse}"
      CONCOURSE_BASIC_AUTH_PASSWORD: "${CONCOURSE_PASSWORD:-changeme}"
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_POSTGRES_USER: "${CONCOURSE_DB_USER:-concourse}"
      CONCOURSE_POSTGRES_PASSWORD: "${CONCOURSE_DB_PASSWORD:-changeme}"

  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
```
