### ISSUE TITLE
resource script '/opt/resource/check []' failed: exit status 5

### ISSUE THREAD

**Issue by soorena776** [swisscom/gitlab-merge-request-resource#24]
Getting the following error: at `repo-mr` resource:
```bash
resource script '/opt/resource/check []' failed: exit status 5

stderr:
jq: error (at <stdin>:1): Cannot index object with number
```

I am setting the following pipeline. The pipeline gets created successfully.

```yaml
resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: mastertinner/gitlab-merge-request-resource
resources:
- name: repo-mr
  type: merge-request
  source:
    uri: ((repo-uri))
    private_token: ((repo-private-token))
    username: ((username))
    password: ((password))
jobs:
- name: test-merge-request
  plan:
  - get: repo
    resource: repo-mr
    trigger: false
  - put: repo-mr
    params:
      repository: repo
      status: running
  on_failure:
    put: repo-mr
    params:
      repository: repo
      status: failed
  on_success:
    put: repo-mr
    params:
      repository: repo
      status: success
```

A few notes:
- Identical `uri`, `username` and `password` works fine in a separate pipeline with a [git resource](https://github.com/concourse/git-resource). 
- The `uri` format is `https://git.mycompany.com/username/project.git`
- Tried a wrong `password` deliberately and got the same error
- Didn't have any luck with using `private_key` either.

Are there any especial configuration needed on the gitlab side? Would appreciate any help.
