### ISSUE TITLE
Incorrect commit status being updated in put

### ISSUE THREAD

**Issue by edtan** [swisscom/gitlab-merge-request-resource#29]
I'm playing around with the example config to learn how to use this resource, but the `put` step appears to be updating the wrong commit.  Here's a sample of my pipeline:

```
---
resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: mastertinner/gitlab-merge-request-resource

resources:
- name: repo
  type: git
  source:
    uri: git@my-domain.com:my-user/demo.git
    branch: master
    private_key: ((gitlab-private-key))
- name: repo-mr
  type: merge-request
  source:
    uri: git@my-domain.com:my-user/demo.git
    private_token: ((gitlab-personal-token))
    private_key: ((gitlab-private-key))

jobs:
- name: test-merge-request
  plan:
  - get: repo
  - get: repo-mr
    trigger: true
  - put: repo-mr
    params:
      repository: repo
      status: running
  on_failure:
    put: repo-mr
    params:
      repository: repo
      status: failed
  on_success:
    put: repo-mr
    params:
      repository: repo
      status: success
```

Suppose the latest commit on `master` of my repo is `aaa111`.  I create a new `feature-branch`, make a new commit `bbb222`, and create a new merge request from this.  The Concourse pipeline picks up the merge request and correct commit (`bbb222`) in `check` and `get`.  However, `put` updates the commit status of the latest commit on `master` (`aaa111`), instead of my merge request commit (`bbb222`).  Should `bbb222`'s commit status be updated instead?
